import { MigrationInterface, QueryRunner } from "typeorm";

export class AddHealthToProtections1656019688926 implements MigrationInterface {
    name = 'AddHealthToProtections1656019688926'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "asset_sites_site_fk"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "asset_sites_asset_fk"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "tokens_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "organization_members_organization_fk"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "organization_members_user_fk"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP CONSTRAINT "site_organizations_site_fk"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP CONSTRAINT "site_organizations_org_fk"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "protection_sites_site_fk"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "protection_sites_protection_fk"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP CONSTRAINT "asset_protections_asset_fk"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP CONSTRAINT "asset_protections_protection_fk"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "organization_members_user_organization_uk"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "health" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "PK_8c15860c160963b1c4d98713ec1"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "PK_e4c7b2513ef24f750e7428ba11d" PRIMARY KEY ("site_id")`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP COLUMN "asset_id"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD "asset_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "PK_e4c7b2513ef24f750e7428ba11d"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "PK_8c15860c160963b1c4d98713ec1" PRIMARY KEY ("site_id", "asset_id")`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "PK_8c15860c160963b1c4d98713ec1"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "PK_b876060382a91835c51ecec90bb" PRIMARY KEY ("asset_id")`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD "site_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "PK_b876060382a91835c51ecec90bb"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "PK_8c15860c160963b1c4d98713ec1" PRIMARY KEY ("asset_id", "site_id")`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "PK_6a8ca5961656d13c16c04079dd3"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD "token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "PK_6a8ca5961656d13c16c04079dd3" PRIMARY KEY ("token")`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_96aac72f1574b88752e9fb00089"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "PK_b3bd68a2e36210a883b174dea15"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP COLUMN "member_id"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD "member_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "PK_b3bd68a2e36210a883b174dea15" PRIMARY KEY ("member_id")`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD "organization_id" character varying`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "PK_256856c7ab20081dd27937d43ed"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "organization_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "PK_256856c7ab20081dd27937d43ed" PRIMARY KEY ("organization_id")`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP CONSTRAINT "PK_77f28ef71e35d2cd2aeac916c6e"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP COLUMN "site_organization_id"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD "site_organization_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD CONSTRAINT "PK_77f28ef71e35d2cd2aeac916c6e" PRIMARY KEY ("site_organization_id")`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD "site_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD "organization_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sites" DROP CONSTRAINT "PK_cc9bfd643a3d4e033198a474db7"`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "site_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sites" ADD CONSTRAINT "PK_cc9bfd643a3d4e033198a474db7" PRIMARY KEY ("site_id")`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "zerto_meta"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "zerto_meta" text`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "veeam_meta"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "veeam_meta" text`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "PK_44628b983f6aa07fdadb40478a9"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "PK_23400398b44279e04a856be80a4" PRIMARY KEY ("site_id")`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP COLUMN "protection_id"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD "protection_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "PK_23400398b44279e04a856be80a4"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "PK_44628b983f6aa07fdadb40478a9" PRIMARY KEY ("site_id", "protection_id")`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "PK_44628b983f6aa07fdadb40478a9"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "PK_97d2213f0bad90ab8fd28b61901" PRIMARY KEY ("protection_id")`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD "site_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "PK_97d2213f0bad90ab8fd28b61901"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "PK_44628b983f6aa07fdadb40478a9" PRIMARY KEY ("protection_id", "site_id")`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP COLUMN "purpose"`);
        await queryRunner.query(`CREATE TYPE "public"."protection_sites_purpose_enum" AS ENUM('protection', 'recovery')`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD "purpose" "public"."protection_sites_purpose_enum" NOT NULL DEFAULT 'protection'`);
        await queryRunner.query(`ALTER TABLE "protections" DROP CONSTRAINT "PK_d64aef43dfb5db1d9f4c6a6e310"`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "protection_id"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "protection_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protections" ADD CONSTRAINT "PK_d64aef43dfb5db1d9f4c6a6e310" PRIMARY KEY ("protection_id")`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "zerto_meta"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "zerto_meta" text`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "veeam_meta"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "veeam_meta" text`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP CONSTRAINT "PK_68d7b76fd4a9e46dca1437d091a"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP COLUMN "asset_protection_id"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD "asset_protection_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD CONSTRAINT "PK_68d7b76fd4a9e46dca1437d091a" PRIMARY KEY ("asset_protection_id")`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP COLUMN "protection_id"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD "protection_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP COLUMN "asset_id"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD "asset_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "PK_ba1dca7766f77b6c475091f860c"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "asset_id"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "asset_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "PK_ba1dca7766f77b6c475091f860c" PRIMARY KEY ("asset_id")`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "zerto_meta"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "zerto_meta" text`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "veeam_meta"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "veeam_meta" text`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "FK_b876060382a91835c51ecec90bb" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "FK_e4c7b2513ef24f750e7428ba11d" FOREIGN KEY ("site_id") REFERENCES "sites"("site_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "FK_8769073e38c365f315426554ca5" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "FK_89bde91f78d36ca41e9515d91c6" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "FK_7062a4fbd9bab22ffd918e5d3d9" FOREIGN KEY ("organization_id") REFERENCES "organizations"("organization_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD CONSTRAINT "FK_40b48d15e23ab6e07675b5d92b2" FOREIGN KEY ("organization_id") REFERENCES "organizations"("organization_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD CONSTRAINT "FK_54d96a8e0f2b8d75a8711306d76" FOREIGN KEY ("site_id") REFERENCES "sites"("site_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "FK_97d2213f0bad90ab8fd28b61901" FOREIGN KEY ("protection_id") REFERENCES "protections"("protection_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "FK_23400398b44279e04a856be80a4" FOREIGN KEY ("site_id") REFERENCES "sites"("site_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD CONSTRAINT "FK_c57c05242c787d7905583b616b3" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD CONSTRAINT "FK_ebd2da699c01395c45f2566c31c" FOREIGN KEY ("protection_id") REFERENCES "protections"("protection_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP CONSTRAINT "FK_ebd2da699c01395c45f2566c31c"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP CONSTRAINT "FK_c57c05242c787d7905583b616b3"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "FK_23400398b44279e04a856be80a4"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "FK_97d2213f0bad90ab8fd28b61901"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP CONSTRAINT "FK_54d96a8e0f2b8d75a8711306d76"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP CONSTRAINT "FK_40b48d15e23ab6e07675b5d92b2"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "FK_7062a4fbd9bab22ffd918e5d3d9"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "FK_89bde91f78d36ca41e9515d91c6"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "FK_8769073e38c365f315426554ca5"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "FK_e4c7b2513ef24f750e7428ba11d"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "FK_b876060382a91835c51ecec90bb"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "veeam_meta"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "veeam_meta" jsonb`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "zerto_meta"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "zerto_meta" jsonb`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "title" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "PK_ba1dca7766f77b6c475091f860c"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "asset_id"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "asset_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "PK_ba1dca7766f77b6c475091f860c" PRIMARY KEY ("asset_id")`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP COLUMN "asset_id"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD "asset_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP COLUMN "protection_id"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD "protection_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP CONSTRAINT "PK_68d7b76fd4a9e46dca1437d091a"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" DROP COLUMN "asset_protection_id"`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD "asset_protection_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD CONSTRAINT "PK_68d7b76fd4a9e46dca1437d091a" PRIMARY KEY ("asset_protection_id")`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "veeam_meta"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "veeam_meta" jsonb`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "zerto_meta"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "zerto_meta" jsonb`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "title" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protections" DROP CONSTRAINT "PK_d64aef43dfb5db1d9f4c6a6e310"`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "protection_id"`);
        await queryRunner.query(`ALTER TABLE "protections" ADD "protection_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protections" ADD CONSTRAINT "PK_d64aef43dfb5db1d9f4c6a6e310" PRIMARY KEY ("protection_id")`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP COLUMN "purpose"`);
        await queryRunner.query(`DROP TYPE "public"."protection_sites_purpose_enum"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD "purpose" text NOT NULL DEFAULT 'protection'`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "PK_44628b983f6aa07fdadb40478a9"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "PK_97d2213f0bad90ab8fd28b61901" PRIMARY KEY ("protection_id")`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD "site_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "PK_97d2213f0bad90ab8fd28b61901"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "PK_44628b983f6aa07fdadb40478a9" PRIMARY KEY ("site_id", "protection_id")`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "PK_44628b983f6aa07fdadb40478a9"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "PK_23400398b44279e04a856be80a4" PRIMARY KEY ("site_id")`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP COLUMN "protection_id"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD "protection_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "protection_sites" DROP CONSTRAINT "PK_23400398b44279e04a856be80a4"`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "PK_44628b983f6aa07fdadb40478a9" PRIMARY KEY ("protection_id", "site_id")`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "veeam_meta"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "veeam_meta" jsonb`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "zerto_meta"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "zerto_meta" jsonb`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "title" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sites" DROP CONSTRAINT "PK_cc9bfd643a3d4e033198a474db7"`);
        await queryRunner.query(`ALTER TABLE "sites" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "sites" ADD "site_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sites" ADD CONSTRAINT "PK_cc9bfd643a3d4e033198a474db7" PRIMARY KEY ("site_id")`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD "organization_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD "site_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP CONSTRAINT "PK_77f28ef71e35d2cd2aeac916c6e"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" DROP COLUMN "site_organization_id"`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD "site_organization_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD CONSTRAINT "PK_77f28ef71e35d2cd2aeac916c6e" PRIMARY KEY ("site_organization_id")`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "title" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "PK_256856c7ab20081dd27937d43ed"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "organization_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "PK_256856c7ab20081dd27937d43ed" PRIMARY KEY ("organization_id")`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD "organization_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD "user_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "PK_b3bd68a2e36210a883b174dea15"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP COLUMN "member_id"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD "member_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "PK_b3bd68a2e36210a883b174dea15" PRIMARY KEY ("member_id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_96aac72f1574b88752e9fb00089"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "user_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD "user_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "PK_6a8ca5961656d13c16c04079dd3"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD "token" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "PK_6a8ca5961656d13c16c04079dd3" PRIMARY KEY ("token")`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "PK_8c15860c160963b1c4d98713ec1"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "PK_b876060382a91835c51ecec90bb" PRIMARY KEY ("asset_id")`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD "site_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "PK_b876060382a91835c51ecec90bb"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "PK_8c15860c160963b1c4d98713ec1" PRIMARY KEY ("site_id", "asset_id")`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "PK_8c15860c160963b1c4d98713ec1"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "PK_e4c7b2513ef24f750e7428ba11d" PRIMARY KEY ("site_id")`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP COLUMN "asset_id"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD "asset_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_sites" DROP CONSTRAINT "PK_e4c7b2513ef24f750e7428ba11d"`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "PK_8c15860c160963b1c4d98713ec1" PRIMARY KEY ("asset_id", "site_id")`);
        await queryRunner.query(`ALTER TABLE "protections" DROP COLUMN "health"`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "organization_members_user_organization_uk" UNIQUE ("organization_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD CONSTRAINT "asset_protections_protection_fk" FOREIGN KEY ("protection_id") REFERENCES "protections"("protection_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_protections" ADD CONSTRAINT "asset_protections_asset_fk" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "protection_sites_protection_fk" FOREIGN KEY ("protection_id") REFERENCES "protections"("protection_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "protection_sites" ADD CONSTRAINT "protection_sites_site_fk" FOREIGN KEY ("site_id") REFERENCES "sites"("site_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD CONSTRAINT "site_organizations_org_fk" FOREIGN KEY ("organization_id") REFERENCES "organizations"("organization_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site_organizations" ADD CONSTRAINT "site_organizations_site_fk" FOREIGN KEY ("site_id") REFERENCES "sites"("site_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "organization_members_user_fk" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "organization_members_organization_fk" FOREIGN KEY ("organization_id") REFERENCES "organizations"("organization_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "asset_sites_asset_fk" FOREIGN KEY ("asset_id") REFERENCES "assets"("asset_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_sites" ADD CONSTRAINT "asset_sites_site_fk" FOREIGN KEY ("site_id") REFERENCES "sites"("site_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
